package com.resolveiq.common.incident;

/**
 * Immutable timeline event types according to PRD §20.
 * Recorded event types: ANOMALY_DETECTED, ALERT_GENERATED, CORRELATION_DISCOVERED,
 * DEPLOYMENT_OBSERVED, CONFIG_CHANGE_OBSERVED, INVESTIGATION_STARTED,
 * INVESTIGATION_COMPLETED, HYPOTHESIS_GENERATED, EVIDENCE_DISCOVERED,
 * HUMAN_COMMENT, SEVERITY_CHANGED, ASSIGNMENT_CHANGED, MITIGATION_APPLIED,
 * MONITORING_STARTED, RESOLVED, CLOSED.
 */
public enum IncidentEventType {
    ANOMALY_DETECTED,
    ALERT_GENERATED,
    CORRELATION_DISCOVERED,
    DEPLOYMENT_OBSERVED,
    CONFIG_CHANGE_OBSERVED,
    INVESTIGATION_STARTED,
    INVESTIGATION_COMPLETED,
    HYPOTHESIS_GENERATED,
    EVIDENCE_DISCOVERED,
    HUMAN_COMMENT,
    SEVERITY_CHANGED,
    STATUS_CHANGED,
    ASSIGNMENT_CHANGED,
    MITIGATION_APPLIED,
    MONITORING_STARTED,
    RESOLVED,
    CLOSED
}
